### ISSUE TITLE
bypassing lamin

### ISSUE THREAD

**Issue by scrab017** [cantinilab/scPRINT#7]
I was wondering whether it might be possible to circumvent the lamin workflow and work with a potentially proprietary dataset?

**Comment by scrab017** [comment]
Yes, is it possible to completely avoid using this package?

**Comment by jkobject** [comment]
Hello, 

You can but you will have to change the parts of the code that rely on this package. 
This package is used by the scDataLoader to manage a set of anndata files for training the model, you will thus have to change this part of scDataLoader to work directly with a list of anndata file path instead of lamin collections

If you don't want to train the model but just do inference, we are only using the bionty package which is related to lamindb. It is used to manage the ontology database versions, (gene info, cell type, tissue, disease, ...) so the model needs it to map ENSEMBL IDs to gene name, UBERON, CL and HsapDV IDs to their respective names too.

Given the license of scPRINT you are clearly allowed to do whatever you want with it and use private dataset on it.

What I am worried about is that you might have a misunderstanding about lamindb and privacy. If you were to explain clearly your reason why you don't want to use this package, I might be able to help better.

Just to state it clearly: You will not connect to lamin servers in any way when doing `lamin init --storage ./testdb --name test --schema bionty`, and you don't need internet access. The only moment where you might need internet access is when you load the ontology mappings with `populate_my_ontologies()`. Once they are loaded locally, you can completely disconnect from internet and run scPRINT inference or training. This is actually what I am doing since the servers on which I train scPRINT don't allow internet access.

Best,

**Comment by jkobject** [comment]
message from user: 
| Got it to work without connecting to lamin as you suggested after setting up a new environment. I'm testing using the o2uniqsx checkpoint from Huggingface on a subset of the data. When running anndata, metrics = embedder(model, anndata, cache=False), I'm getting a KeyError: 'CL:0011024'. Do you have any suggestions on how to handle this?

did you ran the `populate_my_ontology()` function?
what happens when you do something like

```python
import bionty as bt
bt.CellType.filter().df()
```

**Comment by jkobject** [comment]
message from user:
> still get an issue

```python
KeyError                                  Traceback (most recent call last)

File ~/miniforge3/envs/scPRenv/lib/python3.10/site-packages/pandas/core/indexes/[base.py:3805](http://base.py:3805/), in Index.get_loc(self, key)

   3804 try:
-> 3805     return self._engine.get_loc(casted_key)
   3806 except KeyError as err:
      ...

 

File index.pyx:167, in pandas._libs.index.IndexEngine.get_loc()

File index.pyx:196, in pandas._libs.index.IndexEngine.get_loc() 

File pandas/_libs/hashtable_class_helper.pxi:7081, in pandas._libs.hashtable.PyObjectHashTable.get_item()

File pandas/_libs/hashtable_class_helper.pxi:7089, in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'CL:0000843'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)

Cell In[7], line 1
----> 1 anndata, metrics = embedder(model, anndata, cache=False)

File ~/miniforge3/envs/scPRenv/lib/python3.10/site-packages/scprint/tasks/[cell_emb.py:173](http://cell_emb.py:173/), in Embedder.__call__(self, model, adata, cache)

   165         model._predict(
   166             gene_pos,
   167             expression,
   168             batch,
   169             pred_embedding=self.pred_embedding,
   170         )
   171         torch.cuda.empty_cache()

--> 173 model.log_adata(name="predict_part_" + str(model.counter))

File ~/miniforge3/envs/scPRenv/lib/python3.10/site-packages/scprint/model/[model.py:1404](http://model.py:1404/), in scPrint.log_adata(self, gtclass, name)
   1402 if not os.path.exists(mdir):
   1403     os.makedirs(mdir)
-> 1404 adata, fig = utils.make_adata(
   1405     self.embs,
   1406     self.classes,
   1407     self.pred if not self.keep_all_cls_pred else None,
   1408     self.attn.get(),
   1409     self.global_step,
   1410     self.label_decoders,
   1411     self.labels_hierarchy,
   1412     gtclass,
   1413     [self.name](http://self.name/) + "_" + name + "_" + str(self.global_rank),
   1414     mdir,
   1415     self.doplot,
   1416 )
   1417 if self.doplot:
   1418     try:
      ...

File ~/miniforge3/envs/scPRenv/lib/python3.10/site-packages/scprint/model/[utils.py:94](http://utils.py:94/), in make_adata(embs, labels, pred, attention, step, label_decoders, labels_hierarchy, gtclass, name, mdir, doplot)

     92 if tr is not None:
     93     adata.obs["conv_" + gtclass] = tr
---> 94 adata.obs[gtclass] = labels
     95 fig = None
     96 if doplot:

File ~/miniforge3/envs/scPRenv/lib/python3.10/site-packages/pandas/core/[frame.py:3945](http://frame.py:3945/), in DataFrame.__getitem__(self, key)
   3943 if self.columns.nlevels > 1:
   3944     return self._getitem_multilevel(key)
-> 3945 indexer = self.columns.get_loc(key)
   3946 if is_integer(indexer):
   3947     indexer = [indexer]

File ~/miniforge3/envs/scPRenv/lib/python3.10/site-packages/pandas/core/indexes/[base.py:3807](http://base.py:3807/), in Index.get_loc(self, key)
   3805     return self._engine.get_loc(casted_key)
   3806 except KeyError as err:
-> 3807     raise KeyError(key) from err

KeyError: 'CL:0000843'
```

solution: it seems the user was using an out of date version of scPRINT which had this known issue, please update to the latest version

**Comment by jkobject** [comment]
it worked
